<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "linuxmcedownloads"
 *
 * Auto generated by Extension Builder 2016-02-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'LinuxMCE Downloads',
	'description' => 'Parse LinuxMCE Downloads',
	'category' => 'plugin',
	'author' => 'Jochen Roth',
	'author_email' => 'rothjochen@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'autoload' => array(
		'psr-4' => array('Linuxmce\\Linuxmcedownloads\\' => 'Classes')
	),
);